name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd C:\inetpub\wwwroot\prod.auctech.in
          powershell -Command "Stop-WebAppPool -Name 'prod.auctech.in'"
          git pull origin main
          powershell -Command "Start-WebAppPool -Name 'prod.auctech.in'"
